# fly.toml app configuration file generated for personal-website-still-sky-4990 on 2025-01-28T02:46:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-website-still-sky-4990'
primary_region = 'yyz'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
